import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
# FIX: We changed HRule to HRFlowable here
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def create_soap_pdf(soap_data: dict, transcript: str):
    """Generates a highly professional medical PDF from the SOAP JSON data."""
    
    buffer = io.BytesIO()
    
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=letter, 
        rightMargin=50, 
        leftMargin=50, 
        topMargin=50, 
        bottomMargin=50
    )
    
    styles = getSampleStyleSheet()
    
    title_style = styles['Heading1']
    title_style.alignment = 1  
    title_style.textColor = colors.HexColor("#1e293b")
    
    section_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        textColor=colors.HexColor("#2563eb"),
        spaceAfter=10,
        spaceBefore=15
    )
    
    body_style = ParagraphStyle(
        'ClinicalBody',
        parent=styles['Normal'],
        fontSize=11,
        leading=16, 
        spaceAfter=8
    )
    
    elements = []
    
    # 1. Hospital/Clinic Header
    elements.append(Paragraph("<b>MedSOAP AI</b> - Clinical Encounter Note", title_style))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(f"<b>Date of Service:</b> {datetime.now().strftime('%B %d, %Y - %H:%M')}", body_style))
    elements.append(Paragraph(f"<b>Generated by:</b> AI Dictation Engine", body_style))
    
    # FIX: Updated the horizontal line syntax
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1"), spaceBefore=15, spaceAfter=15))
    
    # 2. The S.O.A.P. Sections
    sections = [
        ("Subjective (History of Present Illness)", soap_data.get("Subjective", [])),
        ("Objective (Physical Exam & Labs)", soap_data.get("Objective", [])),
        ("Assessment (Diagnoses)", soap_data.get("Assessment", [])),
        ("Plan (Treatment & Follow-up)", soap_data.get("Plan", []))
    ]
    
    for title, items in sections:
        elements.append(Paragraph(title, section_style))
        
        if items and len(items) > 0:
            for item in items:
                text = item.get("text", "") if isinstance(item, dict) else str(item)
                elements.append(Paragraph(f"• {text}", body_style))
        else:
            elements.append(Paragraph("<i>None noted.</i>", body_style))
            
    # 3. Add Raw Transcript at the bottom for legal/auditing purposes
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1"), spaceBefore=25, spaceAfter=15))
    elements.append(Paragraph("Raw Audio Transcript", section_style))
    
    transcript_text = transcript if transcript else "No audio transcript recorded."
    elements.append(Paragraph(f"<i>\"{transcript_text}\"</i>", ParagraphStyle(
        'Transcript', parent=body_style, textColor=colors.HexColor("#64748b"), fontSize=10
    )))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer